package search

import (
	"context"
	"database/sql"
	"encoding/csv"
	"fmt"
	"math"
	"os"
	"strconv"
	"sync"
	"time"
)

// EmbeddingStore holds all artist embeddings in memory
type EmbeddingStore struct {
	mu         sync.RWMutex
	embeddings map[string][]float64 // artistID -> embedding vector
	dimension  int                  // embedding dimension (e.g., 32)
}

// GlobalEmbeddingStore is the singleton instance
var GlobalEmbeddingStore *EmbeddingStore

// NewEmbeddingStore creates a new embedding store
func NewEmbeddingStore() *EmbeddingStore {
	return &EmbeddingStore{
		embeddings: make(map[string][]float64),
		dimension:  0,
	}
}

// LoadFromCSV loads embeddings from the CSV file generated by PecanPy
// Expected format: artist_id,emb_0,emb_1,...,emb_31
func (es *EmbeddingStore) LoadFromCSV(filepath string) error {
	es.mu.Lock()
	defer es.mu.Unlock()

	file, err := os.Open(filepath)
	if err != nil {
		return fmt.Errorf("failed to open embeddings file: %w", err)
	}
	defer file.Close()

	reader := csv.NewReader(file)

	// Read header to determine dimension
	header, err := reader.Read()
	if err != nil {
		return fmt.Errorf("failed to read header: %w", err)
	}

	// Find embedding columns (all except artist_id)
	embColStart := -1
	for i, col := range header {
		if col == "emb_0" {
			embColStart = i
			break
		}
	}

	if embColStart == -1 {
		return fmt.Errorf("could not find emb_0 column in CSV header")
	}

	es.dimension = len(header) - embColStart

	// Read all rows
	count := 0
	for {
		record, err := reader.Read()
		if err != nil {
			break // EOF or error
		}

		artistID := record[0]
		embedding := make([]float64, es.dimension)

		// Parse embedding values
		for i := 0; i < es.dimension; i++ {
			val, err := strconv.ParseFloat(record[embColStart+i], 64)
			if err != nil {
				return fmt.Errorf("failed to parse embedding for artist %s: %w", artistID, err)
			}
			embedding[i] = val
		}

		es.embeddings[artistID] = embedding
		count++
	}

	fmt.Printf("Loaded %d artist embeddings (dimension=%d)\n", count, es.dimension)
	return nil
}

// LoadFromDB loads embeddings from the artist_embeddings_n2v table
func (es *EmbeddingStore) LoadFromDB(store *Store) error {
	es.mu.Lock()
	defer es.mu.Unlock()

	if store == nil || store.DB == nil {
		return fmt.Errorf("store or database is nil")
	}

	// Create context with timeout
	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()

	// Query to get all embeddings
	// Assuming the table has columns: artist_id, emb_0, emb_1, ..., emb_31
	query := `
		SELECT
			artist_id,
			emb_0, emb_1, emb_2, emb_3, emb_4, emb_5, emb_6, emb_7,
			emb_8, emb_9, emb_10, emb_11, emb_12, emb_13, emb_14, emb_15,
			emb_16, emb_17, emb_18, emb_19, emb_20, emb_21, emb_22, emb_23,
			emb_24, emb_25, emb_26, emb_27, emb_28, emb_29, emb_30, emb_31
		FROM artist_embeddings_n2v
		ORDER BY artist_id
	`

	rows, err := store.DB.QueryContext(ctx, query)
	if err != nil {
		return fmt.Errorf("failed to query embeddings from database: %w", err)
	}
	defer rows.Close()

	// Determine dimension from query (32 embedding columns)
	es.dimension = 32

	count := 0
	for rows.Next() {
		var artistID string
		embedding := make([]float64, es.dimension)

		// Create scan destinations using sql.NullFloat64 for safe NULL handling
		scanDest := make([]interface{}, es.dimension+1)
		scanDest[0] = &artistID

		nullFloats := make([]sql.NullFloat64, es.dimension)
		for i := 0; i < es.dimension; i++ {
			scanDest[i+1] = &nullFloats[i]
		}

		// Scan the row
		if err := rows.Scan(scanDest...); err != nil {
			return fmt.Errorf("failed to scan embedding row: %w", err)
		}

		// Convert NullFloat64 to float64 (use 0.0 for NULL values)
		for i := 0; i < es.dimension; i++ {
			if nullFloats[i].Valid {
				embedding[i] = nullFloats[i].Float64
			} else {
				embedding[i] = 0.0
			}
		}

		es.embeddings[artistID] = embedding
		count++
	}

	if err := rows.Err(); err != nil {
		return fmt.Errorf("error iterating embedding rows: %w", err)
	}

	fmt.Printf("Loaded %d artist embeddings from database (dimension=%d)\n", count, es.dimension)
	return nil
}

// GetEmbedding retrieves the embedding for an artist ID
func (es *EmbeddingStore) GetEmbedding(artistID string) ([]float64, bool) {
	es.mu.RLock()
	defer es.mu.RUnlock()

	emb, ok := es.embeddings[artistID]
	return emb, ok
}

// CosineSimilarity computes cosine similarity between two embeddings
// Returns a value in [-1, 1], where 1 means identical direction
func CosineSimilarity(a, b []float64) float64 {
	if len(a) != len(b) {
		return 0.0
	}

	var dotProduct, normA, normB float64
	for i := 0; i < len(a); i++ {
		dotProduct += a[i] * b[i]
		normA += a[i] * a[i]
		normB += b[i] * b[i]
	}

	if normA == 0 || normB == 0 {
		return 0.0
	}

	return dotProduct / (math.Sqrt(normA) * math.Sqrt(normB))
}

// EuclideanDistance computes L2 distance between two embeddings
func EuclideanDistance(a, b []float64) float64 {
	if len(a) != len(b) {
		return math.MaxFloat64
	}

	var sum float64
	for i := 0; i < len(a); i++ {
		diff := a[i] - b[i]
		sum += diff * diff
	}

	return math.Sqrt(sum)
}

// AStarHeuristic computes the A* heuristic using embeddings
// Returns a distance estimate from current to target
// Lower values = closer in embedding space = better heuristic
func (es *EmbeddingStore) AStarHeuristic(currentID, targetID string) float64 {
	currentEmb, ok1 := es.GetEmbedding(currentID)
	targetEmb, ok2 := es.GetEmbedding(targetID)

	// If embeddings not found, return neutral heuristic
	if !ok1 || !ok2 {
		return 0.0
	}

	// Convert cosine similarity [-1, 1] to distance [0, 2]
	// Higher similarity -> lower distance
	similarity := CosineSimilarity(currentEmb, targetEmb)
	distance := 1.0 - similarity

	return distance
}

// InitEmbeddings is a convenience function to initialize the global store from CSV
func InitEmbeddings(filepath string) error {
	GlobalEmbeddingStore = NewEmbeddingStore()
	return GlobalEmbeddingStore.LoadFromCSV(filepath)
}

// InitEmbeddingsFromDB is a convenience function to initialize the global store from database
func InitEmbeddingsFromDB(store *Store) error {
	GlobalEmbeddingStore = NewEmbeddingStore()
	return GlobalEmbeddingStore.LoadFromDB(store)
}
